name: pyscienv
channels:
  - conda-forge
dependencies:
  - python = 3.10
  - numpy = 1.23.0
  - matplotlib
  - rocketpy
  - pandas
  - CoolProp
  - pyyaml
  - qiskit
  - qiskit-ibm-runtime
  - pylatexenc
